using UnityEngine;
using UnityEditor;

public class SafePathExporter
{
    [MenuItem("Simulator/SafePath 코드로 복사하기")]
    public static void ExportToCode()
    {
        int safeLayer = LayerMask.NameToLayer("SafePath");

        if (safeLayer == -1)
        {
            Debug.LogError("SafePath 레이어가 없습니다! 오타가 없는지 확인해주세요.");
            return;
        }

        Transform[] allTransforms = Object.FindObjectsByType<Transform>(FindObjectsInactive.Include, FindObjectsSortMode.None);

        // 🚀 [추가됨] 자동 생성된 월드의 최상단 폴더(SimWorld)를 찾습니다.
        GameObject simWorld = GameObject.Find("SimWorld");

        string code = "public static void GenerateCustomSafePath(Transform root)\n{\n";
        code += "    int safeLayer = LayerMask.NameToLayer(\"SafePath\");\n\n";

        int count = 0;
        foreach (var t in allTransforms)
        {
            // SimWorld 폴더 안에 속해있는지 검사 (계단, 에스컬레이터, 엘리베이터 거르기 위함)
            bool isAutoGenerated = (simWorld != null && t.IsChildOf(simWorld.transform));

            // SafePath 레이어이고, 형태가 있으며, 🚀"자동 생성된 건물의 부품이 아닐 때만(유저가 만든 것만)"🚀 복사!
            if (t.gameObject.layer == safeLayer && t.GetComponent<MeshRenderer>() != null && !isAutoGenerated)
            {
                code += $"    var obj{count} = GameObject.CreatePrimitive(PrimitiveType.Cube);\n";
                code += $"    obj{count}.transform.SetParent(root);\n";
                code += $"    obj{count}.transform.position = new Vector3({t.position.x}f, {t.position.y}f, {t.position.z}f);\n";
                code += $"    obj{count}.transform.rotation = Quaternion.Euler({t.eulerAngles.x}f, {t.eulerAngles.y}f, {t.eulerAngles.z}f);\n";
                code += $"    obj{count}.transform.localScale = new Vector3({t.localScale.x}f, {t.localScale.y}f, {t.localScale.z}f);\n";
                code += $"    obj{count}.layer = safeLayer;\n";
                code += $"    obj{count}.GetComponent<MeshRenderer>().enabled = false;\n\n";
                count++;
            }
        }
        code += "}\n";

        if (count > 0)
        {
            GUIUtility.systemCopyBuffer = code;
            Debug.Log($"[성공] 유저님이 직접 만든 {count}개의 블록 코드만 완벽하게 추출되었습니다! Ctrl+V 하세요.");
        }
        else
        {
            Debug.LogWarning("[실패] 유저님이 직접 만든 SafePath 큐브를 찾을 수 없습니다.");
        }
    }
}